language: node_js
cache: yarn
node_js:
  - "8"

before_script:
  - yarn add global codecov

script:
  - yarn lint
  - yarn test -- --bail --coverage

after_success:
  - codecov

before_deploy:
  - npm -g install firebase-tools
  - yarn build

deploy:
  provider: script
  skip_cleanup: true
  script: firebase deploy --token $FIREBASE_TOKEN --non-interactive
  on:
    branch: master
