language: node_js
node_js:
  - "8"

before_script:
  - yarn add global codecov
  - yarn add global firebase-tools

script:
  - yarn lint
  - yarn test -- --bail --coverage

after_success: 
  - codecov

deploy:
  provider: script
  skip_cleanup: true
  script: yarn build && firebase deploy --token $FIREBASE_TOKEN
  on:
    branch: master
