language: node_js
cache: yarn
node_js:
  - "8"

before_script:
  - yarn global add codecov

script:
  - yarn lint
  - yarn test -- --bail --coverage

after_success:
  - codecov
  - yarn build

before_deploy:
  - yarn global add firebase-tools

deploy:
  provider: script
  skip_cleanup: true
  script: firebase deploy --token $FIREBASE_TOKEN --non-interactive
  on:
    branch: master
