language: node_js
cache: yarn
node_js:
  - "8"

script:
  - yarn lint
  - yarn test -- --bail --coverage

after_success:
  - yarn add global codecov
  - codecov

before_deploy:
  - npm -g install firebase-tools

deploy:
  provider: script
  skip_cleanup: true
  script: yarn build && firebase deploy --token $FIREBASE_TOKEN
  on:
    branch: master
